### ISSUE TITLE
Build error when using ros-noetic-pybind11-catkin ubuntu package

### ISSUE THREAD

**Issue by rowanborder** [leggedrobotics/raw_image_pipeline#12]
If you have the `ros-noetic-pybind11-catkin` ubuntu package installed then you may encounter the following error when building `raw_image_pipeline_python`:

`catkin_ws/src/raw_image_pipeline/raw_image_pipeline_python/thirdparty/cvnp/cvnp/cvnp.cpp:26:55: error: ‘class pybind11::dtype’ has no member named ‘char_’`

You need to remove this package and use the `git@github.com:leggedrobotics/pybind11_catkin.git` source repository instead.

**Comment by mmattamala** [comment]
@rowanborder do you mind if I close this as `leggedrobotics/pybind11_catkin` is listed as a dependency on the README? Perhaps I could make that more clear.

The error you reported is because the one in the PPAs is 2.5 while Github's is 2.10, which has a new API that cvnp relies on.

**Comment by rowanborder** [comment]
@mmattamala Sure, absolutely. Would be good to include it as a note in the README though for others who encounter the same error.
